name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Consider updating to the latest version if compatible with your setup

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_SERVER }}
        port: 22 # Default SFTP port, adjust if your server uses a different port
        ssh_private_key: ${{ secrets.FTP_PASSWORD }} # Assuming the password field contains your SSH private key
        local_path: ./ # Adjust this if you need to deploy a specific subdirectory
        remote_path: /path/to/your/server/directory # Adjust to the actual path on your server
        args: -o StrictHostKeyChecking=no # Additional SSH options if needed
